name: amazon-sales-dashboard
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - matplotlib
  - plotly
  - altair
  - shiny
  - shinywidgets
  - geopandas
  - folium
  - scikit-learn
  - scipy
  - jupyterlab
  - ipykernel
  - pip:
      - shiny
